### ISSUE TITLE
Download management command doesn't work for all datasets

### ISSUE THREAD

**Issue by alastair** [MTG/similarity-annotator#109]
I tried to use the `download_annotations` management command to download annotations for the **Riyaz** dataset, but it didn't add the files to the `/export` directory.

It looks like the exporter expects datasets to all be in the `/import` directory: https://github.com/MTG/similarity-annotator/blob/34085681f547bf1ec6f2cba1af38a68c3e0b1731/annotation/management/commands/download_annotations.py#L34
but some datasets have `original_filename` as `/riyaz_data` or `/mtg-shared`.

Perhaps we should have a configuration option for the export directory and all exports always get stored here regardless of the first component of the filename

**Comment by Oriol-Romani-BA** [comment]
Sure, I'll do it
