### ISSUE TITLE
Handle uploading of same file name

### ISSUE THREAD

**Issue by Oriol-Romani-BA** [MTG/similarity-annotator#11]

**Comment by Oriol-Romani-BA** [comment]
Fixed in 8d8380d662aafa8c9c9f486d6c421e0f102b9cfc

**Comment by alastair** [comment]
Did you know that you can close issues directly from the commit message? https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by Oriol-Romani-BA** [comment]
Nice!
