### ISSUE TITLE
trying to install libavcodec-extra-53 but facing error

### ISSUE THREAD

**Issue by artinegi1607** [MTG/similarity-annotator#112]
I am using ubuntu 18 and I got the below error.
 Any help would be appreciated.

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libavcodec-extra-53 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libavcodec-extra-53' has no installation candidate

**Comment by alastair** [comment]
In Ubuntu 18.04 this package has been upgraded and should now be available as `libavcodec-extra57`
