### ISSUE TITLE
 All Tiers should be visible on the same page.

### ISSUE THREAD

**Issue by meghanasudhi** [MTG/similarity-annotator#18]
In Indian Music, the lyrics and notes are interdependent. It would be nice to see all the tiers on the same page!

**Comment by meghanasudhi** [comment]
Related tiers and copying the timestamps to other tier.

**Comment by meghanasudhi** [comment]
Name to every segment should not be mandatory and few lessons in Carnatic music have silences inbetween the notes and I  do not segment  them with a name and would be left blank

**Comment by meghanasudhi** [comment]
After the annotation and when we click submit - no pop up is seen

**Comment by Oriol-Romani-BA** [comment]
We discussed about this and we decided that we could keep a different interface for each Tier if we copy the annotations from a upper level tier into the next one. 
For instance, having a first tier _melody_ and a second one _notes_,  the segments from _melody_ should be copied into _notes_. Those copied segments won't have the names from the original ones and we should be able to subsegment them into new segments.

**Comment by Oriol-Romani-BA** [comment]
To do this we should also build a way to link tiers so the annotations from one appear on the next one

**Comment by Oriol-Romani-BA** [comment]
Fixed 044368a5feebe04da2ce6e758a409f001454e6dc, 384f8f9a44561d500285fb1d9d832b85000714a2, 1548052aa9958d043a25d42ffc01d3d511e5eb0c and 74842f869c89199e04ec40497cd0659fea9313b0
