### ISSUE TITLE
Zoom doesn't get back to original size

### ISSUE THREAD

**Issue by Oriol-Romani-BA** [MTG/similarity-annotator#34]
After zooming in, when you zoom out to original position the waveform doesn't come back to the original size

**Comment by Oriol-Romani-BA** [comment]
It seesm it could be related with wavesurfer.js itself, as it also happens in [here](http://codepen.io/katspaugh/pen/GozaaG/)

**Comment by andrebola** [comment]
Changed from slider to a dropdown, so we can check if this solves the problem.
Commit https://github.com/MTG/similarity-annotator/commit/46a9b986217cd5c43040cffbd13416904d5dea5d
