### ISSUE TITLE
Annotations created in child tier shouldn't appear in parent tier

### ISSUE THREAD

**Issue by Oriol-Romani-BA** [MTG/similarity-annotator#55]
By now when two tiers are related the annotations created in one of them are copied to the other one, as is the need of riyaz dataset. This could be changed to a new kind of relationship between tiers that would specify this behavior.

We would like to have a hierarchical relationship, so annotations in parent appear in child but not the other way around. We should keep a link between them so, even if a segment is subsegmented in the child tier, modifying the "shared" start time or endtime will modify the segments both in parent and child.

**Comment by ronggong** [comment]
I tried to annotate the reference file. The segments annotated in parent tier didn't appear in child tier. In non-reference file annotation, this is fine.

**Comment by ronggong** [comment]
For non-reference sound annotation, if a parent tier has more than one child tiers, starting from the second one (including), the segments of the parent tier will not be inherited.
