### ISSUE TITLE
Show spectrogram

### ISSUE THREAD

**Issue by Oriol-Romani-BA** [MTG/similarity-annotator#61]
@Rafael-Caro asked for an option in the segmentation interface to show the spectrogram. 
We should have both options; waveform and spectrogram.
Having this option could be defined also in the 'Rubric.json' file  in case some datasets don't want to allow this option

**Comment by ronggong** [comment]
It's better that we can set the lower and upper frequency bounds for displaying the spectrogram. If this takes too much time to do. We can fix the upper frequency bound to 5000 Hz, as it covers more or less the human speech/singing frequency range.

**Comment by andrebola** [comment]
I don't think we can control de range of frequencies right now since is not allowed by the library: http://wavesurfer-js.org/example/spectrogram/

**Comment by ronggong** [comment]
@andrebola don't worry, I think to display the whole frequency range is also fine, the importance for us is being able to clearly see the syllable boundary.

**Comment by Oriol-Romani-BA** [comment]
Showing the spectrogram makes the interface slower, it could be nice to reduce spectrogram resolution if possible

**Comment by andrebola** [comment]
I reduced the resolution of the spectrogram to the half, but I'm not sure if the performance changed too much. It's more blurry now.
