### ISSUE TITLE
Go back to "MAIN MENU" button required

### ISSUE THREAD

**Issue by meghanasudhi** [MTG/similarity-annotator#62]
After the last song of the exercise going back is tedious hence going to main menu or the page containing all the exercises is required.

**Comment by Oriol-Romani-BA** [comment]
hi @meghanasudhi , from which page you would like to go back to exercises list?

**Comment by Oriol-Romani-BA** [comment]
We provide links to different sections in 812fa4703d657e4fd4a4a79f4cb8ca69a4de1946
