### ISSUE TITLE
Edit tiers

### ISSUE THREAD

**Issue by Rafael-Caro** [MTG/similarity-annotator#66]
Allow the user to edit tiers:
- [x] Rename a tier
- [x] Change the parent / child relationship
- [x] Delete a tier
- [ ] Change the order in which tiers are listed (this is not important, but nice to have)

**Comment by Oriol-Romani-BA** [comment]
hey @Rafael-Caro, about the last task you asked for, could we raise down its priority?

**Comment by Rafael-Caro** [comment]
@oriolromani Yes, no problem. Actually, could I change the priority myself?

**Comment by Oriol-Romani-BA** [comment]
I think you should be able to do it
