### ISSUE TITLE
Display parent / child relationship

### ISSUE THREAD

**Issue by Rafael-Caro** [MTG/similarity-annotator#67]
Show the relationship between parents and childs in the tiers list, or in any other display.

**Comment by Oriol-Romani-BA** [comment]
We should change the tier creation form to allow users create the different tier relationships

**Comment by Oriol-Romani-BA** [comment]
The tier creation form should be modified to behave as following:

- [x] when selecting timestmap annotations only tiers of this kind should appear on the following sections

- [x] selecting a tier as being "sync tier" shouldn't allow the user to select the same tier as parent tier
