### ISSUE TITLE
Stats on how many files done in Riyaz

### ISSUE THREAD

**Issue by meghanasudhi** [MTG/similarity-annotator#79]
A counter of how many annotations are done should be seen so that its a check for annotators.
I know about the color coding but a hard coded number is great!

**Comment by Oriol-Romani-BA** [comment]
Hey @meghanasudhi, could you specify which stats you would like to see and in which page?

**Comment by meghanasudhi** [comment]
@oriolromani  : Just saying 'x' number of files are completed until now
Eg : 182 .
A number is sufficient or just counting the number of greens!

**Comment by Oriol-Romani-BA** [comment]
This is fixed in f62558a8178d1fc187da9a0410490b0ab02c7e71 and already deployed in production.
