### ISSUE TITLE
shortcut to play sound (space bar plays both the reference and sound to annotate player)

### ISSUE THREAD

**Issue by meghanasudhi** [MTG/similarity-annotator#88]
Need a short cut to specifically play 'the sound to annotate' player clicking is too tedious!

**Comment by Oriol-Romani-BA** [comment]
This issue is really similar to #73

**Comment by Oriol-Romani-BA** [comment]
This is treated in 7eecb72a6b1951d6662e4b359435c11992dabeab in a slight different way; space bar only plays/stop a single sound if before you have clicked the play button of that sound
