### ISSUE TITLE
Next doesn't work after Page 2

### ISSUE THREAD

**Issue by meghanasudhi** [MTG/similarity-annotator#94]
https://simannotator.mtg.upf.edu/256/sound_list/?page=3&page=2
In the above link it shows it has 5 pages of sounds and the way its navigated to next page is through 'next' it doesnt work after page 2.
Similar issue here also
https://simannotator.mtg.upf.edu/250/sound_list/?page=3&page=2

**Comment by Oriol-Romani-BA** [comment]
Repeated issue #93
