### ISSUE TITLE
Labels displaced while segmenting

### ISSUE THREAD

**Issue by Rafael-Caro** [MTG/similarity-annotator#98]
When I was dividing existing segments in a child tier (5.1), the labels were moved from their original positions. When I click a play button or move the scrolling bar (I'm using 4x zoom) at the bottom they go back to their original place. This is very unconvenient, because the label might even go outside the visible window.
(Using Windows 10 and Chrome 56)

**Comment by Rafael-Caro** [comment]
I just realised that the labels are displaced when click "i" for a new segment.
Here's a pic of the phenomenon:
![captura](https://cloud.githubusercontent.com/assets/6338660/24158098/4d059d1e-0e96-11e7-8e17-371d82aec716.JPG)
So, the labels shown here belong to the first segments of the audio, that don't even appear in the displayed window.

**Comment by ronggong** [comment]
I had the same issue, which makes it is impossible to listen the segment.

**Comment by Rafael-Caro** [comment]
This is not a very important issue, compared with the others. Because by clicking in any label or just moving the scrolling bar a bit the labels go back to the original place. I would give less priority to this issue than to the others (I swear I cannot find the way to add priority...)
