### ISSUE TITLE
No possibility of dragging boundaries in zoom 8x

### ISSUE THREAD

**Issue by Rafael-Caro** [MTG/similarity-annotator#99]
When I use zoom 8x I cannot drag a newly created boundary, only the inherited ones from parent tiers. The cursor doesn't even change when I put it on top of a boundary

**Comment by Oriol-Romani-BA** [comment]
I am not able to reproduce this issue

**Comment by andrebola** [comment]
commit e8c5ce233c8ebd08b53a0f30bbcac2e72e89bfd7
